### ISSUE TITLE
Need way to set AD or LDAP as auth source & disable LDAP referrals

### ISSUE THREAD

**Issue by C0missar** [F5Networks/f5-ansible#1182]
##### ISSUE TYPE

 
- Feature request

##### COMPONENT NAME

bigip_device_auth_ldap, or new module

##### ANSIBLE VERSION

```
ansible 2.7.1
  config file = /home/sxw455/.ansible.cfg
  configured module search path = [u'/home/sxw455/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /home/sxw455/.local/lib/python2.7/site-packages/ansible
  executable location = /home/sxw455/.local/bin/ansible
  python version = 2.7.15rc1 (default, Apr 15 2018, 21:51:34) [GCC 7.3.0]
```

##### PYTHON VERSION

```
Python 2.7.15rc1
```

##### BIGIP VERSION

```
Sys::Version
Main Package
  Product     BIG-IP
  Version     13.1.1
  Build       0.0.4
  Edition     Final
  Date        Fri Jul 20 17:55:49 PDT 2018

```

##### LIBRARY VERSIONS

```
bigsuds==1.0.6
f5-sdk==3.0.20
```

##### OS / ENVIRONMENT

Win10/WSL/Ubuntu 18.0.4

##### SUMMARY

Once bigip_device_auth_ldap is called to configure an LDAP provider, there is no way to set it as the system auth source.  The workaround is to use bigip_command to issue the following:

  "tmsh modify auth source { fallback true type active-directory }"

We also need a way to modify /etc/openldap/ldap.conf in order to disable referrals.  At present, we issue the following command from the CLI manually, since the bigip_command module will not allow bash commands:

  "sed -i '/.*REFERRALS.*/d' /etc/openldap/ldap.conf; sed -i '$a REFERRALS\tno' /etc/openldap/ldap.conf"

The bigip_command module says that it does tmsh and bash in the header, but in the detailed description it states that bash is not supported.  The documentation should be corrected, or the forced "tmsh" prefix should be removed.

##### STEPS TO REPRODUCE

```
https://gist.github.com/C0missar/598ff2ffaf94d577c3a7324942bd2d60
```

##### ACTUAL RESULTS

```

```

**Comment by Cajga** [comment]
Same issue here with the auth source. +1 for the feature request.

**Comment by wojtek0806** [comment]
FMFA-239

**Comment by C0missar** [comment]
I've started transitioning my bigip module usage to REST calls in Ansible rather than wait any longer for those modules to mature.  As near as I can tell, that's what the bigip modules call anyway.

Stan

**Comment by wojtek0806** [comment]
@C0missar I will add the option for auth sources to the auth_ldap, in fact auth_ldap can be either 'cert-ldap' and 'ldap' active-directory needs a separate module (i need to see if parameters are different if they aren't we just fold it under auth_ldap). BIGIP command module runs bash commands, but it does that via: 'tmsh run util /bash <command>' method, which for some commands work and for some it does not. I think since you reported it we have make such note in the documentation. For manipulating .conf file on the unit if there is not a safe TMSH command or REST endpoint that does it, we simply won't implement it.
