### ISSUE TITLE
RFE bigip_device_facts scope to partition

### ISSUE THREAD

**Issue by lopf** [F5Networks/f5-ansible#1248]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
bigip_device_facts

##### ANSIBLE VERSION
```
ansible 2.7.8
```

##### PYTHON VERSION
```
Python 3.7.1
```

##### BIGIP VERSION
```
12.1.x
```

##### SUMMARY

We're using the `bigip_device_facts` module and iterate over the facts. We have many objects (of the same kind) and so the list is very long. Even with `no_log: true`, it spams the console heavily. 
For such tasks, we're only interested in objects of a particular partition. Hence, we would like to be able to limit the facts gathering (for scoped objects) to a defined partition.

**Comment by wojtek0806** [comment]
i am afraid we will not be doing this, as device facts also gathers data that is not in any partition, if you want to display a subset of items rather than the all list, you can filter them using using jq or jinja filters.

Some examples of jq and jinja we use in our integration testing:

https://github.com/F5Networks/f5-ansible/blob/devel/test/integration/targets/bigip_device_facts/tasks/issue-01094.yaml#L18

https://github.com/F5Networks/f5-ansible/blob/devel/test/integration/targets/bigip_device_facts/tasks/issue-00897.yaml#L87

https://github.com/F5Networks/f5-ansible/blob/devel/test/integration/targets/bigip_device_facts/tasks/issue-00897.yaml#L88

You can read more about this here:
http://jmespath.org/examples.html

**Comment by lopf** [comment]
thanks for the hints.
