### ISSUE TITLE
Confusion regarding Server in module and Hosts from Inventory

### ISSUE THREAD

**Issue by compyy** [F5Networks/f5-ansible#130]
No
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

bigip_facts
##### ANSIBLE VERSION

```
ansible 2.4.0
  config file = /home/beta/BICS/ansible.cfg
  configured module search path = [u'/home/beta/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python2.7/dist-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.13 (default, Jan 19 2017, 14:48:08) [GCC 6.3.0 20170118]
```

##### PYTHON VERSION

```
Python 2.7.13
```

##### BIGIP VERSION

```
11.6.1 HF2
```

##### OS / ENVIRONMENT

N/A
##### SUMMARY

My playbook runs fine for all 18 hosts defined in host file, i still cannot understand what is the use of Server: in playbook, if i remove it and mention "{{ ansible_host }}" then playbook doesnt work and replaces "{{ ansible_host }}" to localhost, i have to provide one valid BIG-IP here, but still it takes all Hosts from host file ? I am confused ? is it bug or expected behaviour ?
##### STEPS TO REPRODUCE

```
# Show version for F5 Hosts
- 
  hosts: F5-DNS
  tasks: 
    - name: Check F5 Server Facts
      bigip_facts:
         server: 10.244.142.36
         user: "{{ansible_user}}"
         password: "{{ansible_pass}}"
         include: "software"
         validate_certs: "no"
      delegate_to: localhost
      register: out

    - debug: msg="{{ out }}"

```

##### ACTUAL RESULTS

```

```

**Comment by compyy** [comment]
ok, i found two issues.
1. DNS
2. Fixed with following playbook.

# Show version for F5 Hosts
- 
  hosts: F5-LB
  environment:
      F5_SERVER: "{{ ansible_host }}"
      F5_USER: "{{ansible_user}}"
      F5_PASSWORD: "{{ansible_ssh_pass}}"
      F5_VALIDATE_CERTS: "false"
      F5_SERVER_PORT: 443

  tasks: 
    - name: Check F5 Server Facts
      bigip_facts:
         include: "software"
      delegate_to: localhost
      register: out

    - debug: msg="{{ out }}"

**Comment by caphrim007** [comment]
@compyy to explain the server and other connection related variables, you need to understand how ansible executes module code.

Ansible reads the YAML file you provide and then based on the values in your playbook's `host:` line, it will transpile the YAML to Python, SCP the python code to the remote machine, and then run `python /path/to/remote/file.py`, on the remote machine, to run the python.

This model does not work with BIG-IP because BIG-IP versions < 12 do not have a copy of Python's `json` module. Without this module (or its sister module `simplejson`) on the remote machine, Ansible cannot read the response from the server when the python code finishes running.

This problem is not specific to BIG-IP though. It happens in many remote systems.

The approach to working around this is to do the following

- change your `connection:` line to be `local, or, change your `hosts:` line to be `localhost`, or, use `delegate_to: localhost` in your Task
- provide the user with the ability to specify "other" connection parameters to the module for the module to use.

What does this accomplish? It accomplishes the following

- Instead of running the python code on the "remote" device, you instead run it on the Ansible controller host; ie, the `localhost`. This is important because the Ansible controller host is __assumed__ to have more up-to-date libraries than any of the remote systems it is connecting to. Or, if it does not, it is __assumed__ that you have sufficient privileges on the Ansible controller host to __install__ those requirements.
- The "new" connection parameters provided to the module (`server`, `user`, `password`, etc) can be used by the module itself to connect to the remote device using "some other method". In the case of the BIG-IP modules, those values that you provide to us are used to connect to the REST API of the BIG-IP.

The value of `{{ ansible_host }}` is the IP address of the current remote device in your inventory. "current" depends on what is in the `hosts:` line of your playbook.

If the hosts that you are running the playbook against are your BIG-IPs, then it's sufficient to set the `server` value to `{{ ansible_host }}`. However, if that is _not_ the case (like may be seen when deploying configuration to a webserver and simultaneously adding that webserver to a pool) that you need to make sure that the value of `server` is the IP address (or hostname if the hostname is a valid DNS entry).

I believe you have fixed whatever error you had, so I'm going to close this issue for now. Feel free to open another issue if needed.
