### ISSUE TITLE
bigip_device_facts['virtual_servers']['name']": "VARIABLE IS NOT DEFINED!: 'list object' has no attribute 'name'"

### ISSUE THREAD

**Issue by Zjemm** [F5Networks/f5-ansible#1331]
### ##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
bigip_device_facts

##### ANSIBLE VERSION
```
2.7.10
```

##### PYTHON VERSION
```
3.7.3
```

##### BIGIP VERSION

```
12.1.2
```

##### SUMMARY
I try to get facts about existing VIP's.
I want to check if a vip already exists before creating one with the same name.
i can list ALL vips, but then i try to filter on only the names but i get an error:

bigip_device_facts['virtual_servers']['name']": "VARIABLE IS NOT DEFINED!: 'list object' has no attribute 'name'"

##### STEPS TO REPRODUCE

```
  roles:
    - role: f5devcentral.f5ansible

  tasks:
    - name: Collect BIG-IP facts
      bigip_device_facts:
        gather_subset:
          - virtual-servers 
        provider: "{{ provider }}"
      register: bigip_device_facts
      delegate_to: localhost


    - name: COMPLETE BIG-IP vips list
      debug:
        var: bigip_device_facts

    - name: DISPLAY ONLY name of the vip
      debug:
        var: bigip_device_facts['virtual_servers']['name']

```

##### EXPECTED RESULTS
only the names of the vips

##### ACTUAL RESULTS

```
bigip_device_facts['virtual_servers']['name']": "VARIABLE IS NOT DEFINED!: 'list object' has no attribute 'name'"
```

but the attribute is there. it looks like because there are multiple vips, the name attribute is not unique anymore and therfor it throws an error, but im not sure.

i want to use facts to check if items like nodes, vips, profiles already exists before making one

**Comment by caphrim007** [comment]
This is happening because virtual servers is a list, but you're treating it like a dictionary.

If you try `['virtual_servers'][0]['name']` you should get the answer you're looking for.

This, however does not answer your question, it just explains the symptom. To get all of the name of all the virtual servers, you need to use the json_query filter.

I'm not on a PC that I can give a good answer atm, but the test/integration/ directory should hold examples for bigip_device_facts that can point you in the right direction.

Otherwise, the jmespath website should offer some assistance because that is what underlies the json_query filter

**Comment by caphrim007** [comment]
` | json_query("virtual_servers[*].name")`

Should produce such a list

**Comment by Zjemm** [comment]
Oh Nice, I didn't know. I did try it with 0.name or some variance. 

I'm not at my PC right now but I'll try your suggestion. Thank you in advance. 

I will let you know the results

**Comment by wojtek0806** [comment]
seeing this was a question we answered closing it now
