### ISSUE TITLE
Feature Request: DNS Listener module

### ISSUE THREAD

**Issue by gullanetworkcode** [F5Networks/f5-ansible#1508]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
bigip_dns_listener

##### ANSIBLE VERSION
```
ansible 2.8.5
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/paulh/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.15+ (default, Jul  9 2019, 16:51:35) [GCC 7.4.0]
```

##### PYTHON VERSION
```
Python 2.7.15+
```

##### BIGIP VERSION
```
Sys::Version
Main Package
  Product     BIG-IP
  Version     12.1.3.7
  Build       0.0.2
  Edition     Point Release 7
  Date        Tue Sep 11 10:03:49 PDT 2018

```

##### OS / ENVIRONMENT
N/A

##### SUMMARY
Would like the ability to create DNS listeners. As these are required for most deployments this would be a good addition

##### EXPECTED RESULTS
Module to create DNS listeners

**Comment by wojtek0806** [comment]
@gullanetworkcode when you open an issue requesting a feature you need to specify the tmsh and/or GUI equivalent to the requested feature. 

In this instance I have found the information, but  in future we will not accept incomplete requests with the minimal information provided. 

Also when asking for a feature specify what parameters would be required as a minimum, otherwise we will use our best judgement to fulfil your request,  as we do not code for everything without specific use case.

An example of what information we are looking for in a feature request can be found here:
https://github.com/F5Networks/f5-ansible/issues/1322

Please supplement your request with the desired parameters for the endpoint if you wish something specific.

**Comment by gullanetworkcode** [comment]
Hi,

The GUI equivalent can be found at  DNS > Delivery > Listeners.

The features I need are:-
Name:
State:
Destination:
Mask: <if destination is network>
VLANs enabled on:
Protocol:
DNS Profile:

The equivalent CLI command to view it is: `list gtm listener`
and gives the following output:-
```gtm listener my_listener {
    address 10.0.0.1
    ip-protocol udp
    mask 255.255.255.255
    port domain
    profiles {
        dns_external { }
        udp_gtm_dns { }
    }
    translate-address disabled
    translate-port disabled
    vlans {
        my_vlan_external
    }
    vlans-enabled
}
```
I guess the CLI command to create it would be:
```create gtm listener gtm listener my_listener { address 10.0.0.1 ip-protocol udp mask 255.255.255.255 port domain profiles { dns_external { } udp_gtm_dns { } } translate-address disabled translate-port disabled vlans { my_vlan_external } vlans-enabled }```

Is that the kind of info you're looking for?

thanks

Paul

**Comment by wojtek0806** [comment]
FMFA-418

**Comment by AndriusV4** [comment]
Hello,

I see that under FMFA-418, bigip_gtm_dns_listener module was created, but it's missing the 'Protocol Profile' and 'DNS Profile' parameters.
Would it be possible to add those?

Example:
test_gtm# list gtm listener

test_listener {
    address 10.10.10.10
    ip-protocol udp
    mask 255.255.255.255
    port domain
    **profiles {
        dns_internal { }
        udp_gtm_dns { }**
    }
    translate-address disabled
    translate-port disabled
    vlans {
        test_vlan
    }
    vlans-enabled
}

Thanks,
Andrius

**Comment by KrithikaChidambaram** [comment]
Hi, please try upgrading to the latest version, it should work. If not, please reach out, thanks!
