### ISSUE TITLE
unit tests for bigip_service

### ISSUE THREAD

**Issue by caphrim007** [F5Networks/f5-ansible#175]
a requirement for upstreaming this module is that unit tests exist for it. these have not yet been written

**Comment by caphrim007** [comment]
closing. no interest in developing this.

**Comment by neozoolook** [comment]
See that this one was closed, and there is documentation in public that states this module exists since ansible 2.2.  There is a need to run 'restart sys service' periodically, example is with syslog-ng processes when installing formatting correction templates.

Can we look at bring this back and also this is the documentation that is visible in public;

https://clouddocs.f5.com/products/orchestration/ansible/devel/modules/bigip_service_module.html
