### ISSUE TITLE
Update Module descriptions/synopsis

### ISSUE THREAD

**Issue by tkam8** [F5Networks/f5-ansible#21]
Hello,  
I'd like to raise an issue for the purpose of updating the below modules with a proper description/synopsis. 

bigip_dns_record_facts (E) - foo
bigip_iapp_service (E) - foo
bigip_iapp_template (E) - foo
bigip_snmp (E) - foo

**Comment by caphrim007** [comment]
@tkam8 thanks for pointing this out! I will add them to the dev log.

**Comment by fieldedge** [comment]
Hello,

Looking at Synopsis on the following site, what is "foo" supposed to mean?  
https://f5-ansible.readthedocs.io/en/latest/modules/list_of_all_modules.html

They seem to not be completed. If it means "not completed", please add it to be more clear.
Thanks,

**Comment by caphrim007** [comment]
@fieldedge yes, modules that are not completed can take a number of forms. Some of the ones that you have noticed include boilerplate code so that I can keep track of what still needs to be written, or so that users will know what is in the pipeline.

There are two ways to know whether something is complete or not.

1. If it's in ansible upstream, it's complete.
2. If the module's test playbooks have a platform listed, it is considered ready for upstreaming, and probably complete. https://f5-ansible.readthedocs.io/en/latest/usage/support.html#how-to-know-which-modules-are-supported

Example test file for module
https://github.com/F5Networks/f5-ansible/blob/master/tests/bigip_device_dns.yaml#L23

The upstreamed modules
https://github.com/ansible/ansible-modules-extras/tree/devel/network/f5
