### ISSUE TITLE
bigip_virtual_server - auto last hop

### ISSUE THREAD

**Issue by martinkyrc** [F5Networks/f5-ansible#2104]
### Is your feature request related to a problem? Please describe.
Using 'bigip_virtual_server' module is not possible change 'auto-lasthop' setting. There is no parameter for this.

'auto-lasthop' feature returns traffic based on sender MAC address (L2 address of the L3 address/gateway that sent packet), not based on routing table (next hop based on L3 address). In some cases is this behavior wrong - e.g. in my case with Cisco ACI. 

Cisco ACI, a.k.a. software-defined data center, manipulates mac addresses for internal communication between End Point Groups. If there is L4-L7 device (in this case 'load-balancer'), 'auto-lasthop' feature returns traffic to wrong mac address - sender's MAC (incoming traffic) and receiver's MAC address (outgoing traffic) is different even though, that L3 address is the same.

Documentation for the auto-lasthop setting: https://support.f5.com/csp/article/K13876

#### Workaround-1:
- configure virtual server using ansible
- then change manualy auto-lasthop using GUI/TMOS configuration

#### Workaround-2:
- first: change auto-lasthop globaly to disabled (using GUI/TMOS)
- then configure virtual server using ansible (no auto-lasthop change for virtual server is needed, becasue default setting is - use global setting)

^^ both workarounds needs some 'manual' change on the BIGIP side.

### Describe the solution you'd like
Add please parameter to change auto-lasthop for bigip_virtual_server module.

**Comment by trinaths** [comment]
@horol - Suggest use AS3 with collections V2. See AS3 schema reference for virutal - https://clouddocs.f5.com/products/extensions/f5-appsvcs-extension/latest/refguide/schema-reference.html#service-http

Refer documentation for using Collections v2 with AS3.https://clouddocs.f5.com/products/orchestration/ansible/devel/f5_bigip/playbook_tutorial.html#create-the-as3-declaration-file

lastHop (string \| Service_HTTP_lastHop) | “default” | “default”, “auto”, “disable”, - | Name of built-in last-hop method or AS3 pointer to last-hop pool (default ‘default’ means use system setting)
-- | -- | -- | --

There will not be any manual configuration required. Share your findings.

**Comment by horol** [comment]
@trinaths - thank you for response and hint. We have currently whole "automation process" based on f5_modules (collection v1). We plan, in the future move it to f5_bigip (collection v2).

Why we are not using collection v2?
- because "Collection is not currently intended to replace the existing f5_modules Collection" (our automation process is build 2y+ ago till now, when f5_modules exists, but f5_bigip not)
- is it not possible mix imperative + declarative prociples, because (Correct me if I'm wrong) when I apply as3 with only part of configuration parameters, whole existing configuration (applied by imperative principle) will be 'lost'.
- in other words, when we change to collection v2, we need change everyting - all our automation process (lot of playbooks, tasks, design of automation... and currently we have not time for it :).

Maybe question:
We are using collection v1 for:
- ltm configuration
- afm configuration
- gtm/dns configuration
- vcmp configuration
- and networking (vlan, ip, routing,...)

Is it possible replace ltm/afm/gtm/dns configuration with as3 (collection v2)? I know, that ltm is no problem, but I have (till now) no experience with as3+afm. Where can I find documentation for this? Of course I can use collection v2 for ltm and collection v1 for afm and other existing parts.

**Comment by trinaths** [comment]
Created INFRAANO-518 for internal tracking.
