### ISSUE TITLE
Drop a partition and all its objects 

### ISSUE THREAD

**Issue by ric79** [F5Networks/f5-ansible#387]
Hello,
I need to drop a partition. The "bigip_partition absent" works only if the partition is empty. At the moment I'm working using tmsh:
 - delete /config/partitions/{{partition_name}}
 - update /config/bigip_base.conf
 ...

I'm trying to rewrite the playbook deleting all partition objects, one by one (ie:  `list ltm  node one-line`).
 Is there a module which gives all the objects defined in a partition (bigig_partition_facts)?

R

**Comment by caphrim007** [comment]
there is no way to know what resources are in a partition. There is also not a safe way to delete a partition outright. there are some comments on devcentral about how people delete the partition folder and reload the config, but that is extremely dangerous because resources can be shared across partitions and your bigip config would refuse to load; essentially bricking your machine and forcing you to load the defaults and start over.

**Comment by caphrim007** [comment]
@ric79 if you want that functionality, you need to be ready to accept the fate that it will deal you.

**Comment by ric79** [comment]
Ok. I m pretty sure that the partition is created by my script and does not contains referenced objects (except for Common). Is it really impossible providing the list of nodes, virtual servers, pools etc created in that partition?

**Comment by caphrim007** [comment]
@ric79 would you be ok with this being a separate parameter to the module? Since it is something that can break your device if used without expertise.

**Comment by ric79** [comment]
Hello,
that's ok. 

However we can also evaluate another strategy. The partition contains own objects or Common shared ones. Now I'm trying to parse these commands in order to get the object names and then to delete them:
```
cd /{{partition_name}};
list net route-domain one-line;
list net vlan one-line;
list net self one-line;
list ltm node one-line;
list ltm monitor one-line;
list ltm pool one-line;
list ltm rule partition | grep "^ltm rule";
list ltm profile one-line;
list ltm virtual one-line;
list net route one-line;
```
Finally, I could call the "absent partition commmand" of partition module in a very safe way. However there is not a quick way to get these facts and I have to parse the output using custom filter_plugins.

What's your opinion about that?

RR

**Comment by caphrim007** [comment]
@ric79 you are encountering the problem which drove me to the decision to not support SSH transports for BIGIP (vs REST). That problem is the parsing of tmsh output.

It is not structured. You're in for an uphill battle, but I wish you the best of luck. If you write your own filter plugin, you may want to investigate the use of the `NetworkConfig` class here in ansible

* https://github.com/ansible/ansible/blob/devel/lib/ansible/module_utils/netcfg.py

It has the ability to parse, sorta, junos output which is what tmsh output is sorta modeled after. It might provide you with sufficient structure to get the data you want programmatically without too much fuss.

**Comment by ric79** [comment]
Thanks, what about of providing a _fact module which describes the partition content? :)

**Comment by caphrim007** [comment]
In the rest API one cannot recursively ask it for everything in a partition, so this would be a largely unsustainable effort. There are over 6000 APIs in BIG-IP, and most of them accept a partition argument. We would need to be able to cover that entire landscape.

It's easier for us to delete the partition and reload the configuration. Taking into consideration that irules can reference any partition.

**Comment by delgadillo22** [comment]
Too much risk for the benefit

**Comment by caphrim007** [comment]
closing this issue as the guidance from PM is that the risk to user configuration is too high, since there is no native feature in bigip to do this (without hacks as was mentioned in the issue). If you need something like this, you may want to investigate using AS3 as it is designed to put things in specific partitions and track what has been put in those partitions so that the entire partition can be deleted
