### ISSUE TITLE
bigip_command sets the 'changed' flag when the device configuration is not changed.

### ISSUE THREAD

**Issue by joelwking** [F5Networks/f5-ansible#391]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

bigip_command
##### ANSIBLE VERSION

```
ansible 2.4.0.0
  config file = /home/administrator/ansible/playbooks/ansible.cfg
  configured module search path = [u'/usr/share/ansible']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.12 (default, Nov 19 2016, 06:48:10) [GCC 5.4.0 20160609]

```

##### PYTHON VERSION

```
python version = 2.7.12
```

##### BIGIP VERSION

```
            "Sys::Version",
            "Main Package",
            "  Product     BIG-IP",
            "  Version     12.1.2",
            "  Build       1.0.271",
            "  Edition     Hotfix HF1",
            "  Date        Fri Apr 28 20:02:07 PDT 2017",

```

##### CONFIGURATION

n/a
##### OS / ENVIRONMENT

n/a
##### SUMMARY

bigip_command sets the 'changed' flag on exit, when the device configuration is not changed. Show commands do not change the device configuration.
##### STEPS TO REPRODUCE

```
$ ansible localhost -m bigip_command -a "commands='show sys license' server=10.255.111.170 password=admin user=admin validate_certs=no"
localhost | SUCCESS => {
    "changed": true,
    "failed": false,
    "stdout": [
        "Can't load license, may not be operational\n"
    ],
    "stdout_lines": [
        [
            "Can't load license, may not be operational",
            ""
        ]
    ]
}

```

##### EXPECTED RESULTS

"changed": false,
##### ACTUAL RESULTS

"changed": true

```

```

**Comment by caphrim007** [comment]
@joelwking this request is complicated for a couple of reasons

1. you can specify multiple commands. If one of them is to modify something, then that will change the return result for everything
2. We cannot know whether something actually changed because tmsh's `create` and `delete` commands returns non-standard output, the `modify` command returns no output, and the return codes from tmsh can sometimes be 100% inaccurate (plus we dont get them from the way we run the remote commands)

So the best that I can offer for now is check the type command of you're running (create, list, show, delete, modify) and set the changed value based on that. But remember point 1 above

**Comment by joelwking** [comment]
For number 1, if any of the commands modifies something, I would expect the changed flag to be set.

**Comment by caphrim007** [comment]
then the fix that I have merged will do that. enjoy
