### ISSUE TITLE
Add ssl-protocol modify sys httpd ssl-protocol "{{ ssl_protocols }}"

### ISSUE THREAD

**Issue by caphrim007** [F5Networks/f5-ansible#587]
modify sys httpd ssl-protocol "{{ ssl_protocols }}"

**Comment by caphrim007** [comment]
@MicSkr give this a try with 2.5

**Comment by rmcolbert** [comment]
This does not work properly. SSL_PROTOCOL must be an ordered list but as currently implemented the values are sorted resulting in all protocols being enabled because the end-result (if applying the default values) is "-SSLv2 -SSLv3 all" which does not work. It must be implemented as "all -SSLv2 -SSLv3"

Removing the sorting should resolve this defect.
