### ISSUE TITLE
bigip_selfip in RD

### ISSUE THREAD

**Issue by hemskgren** [F5Networks/f5-ansible#6]
Hi

The bigip_vlan have the option to add vlan in Route_domain.
But i missing the option to add selfip in Route_domain.

From bigsuds script.

b.Management.Partition.set_default_route_domain(partitions = ['LB-EXT'],route_domains = ['7'])
# 

b.Management.Partition.set_active_partition('LB-EXT')
# 

print "# Set Vlan IP:"
print(b.Networking.SelfIPV2.get_list())
b.Networking.SelfIPV2.create(self_ips = ['vlan7'],vlan_names = ['vlan7'],addresses = ['1.1.1.2'],netmasks = ['255.255.255.248'],traffic_groups = ['traffic-group-local-only'],floating_state
s = ['STATE_DISABLED'])
# print(b.Networking.SelfIPV2.get_list())

print "# Set Vlan-vip IP:"
b.Networking.SelfIPV2.create(self_ips = ['vlan7-vip'],vlan_names = ['vlan7'],addresses = ['1.1.1.1'],netmasks = ['255.255.255.248'],traffic_groups = ['traffic-group-1'],floating_states = [
'STATE_DISABLED'])
print(b.Networking.SelfIPV2.get_list())
# 

regards
Christer

**Comment by caphrim007** [comment]
@hemskgren from what I'm able to make of your example and the SOAP docs, it looks like this request (and even the VLAN one, but I have to look at the API) may be best served by the bigip_partition module coupled with this module.

I know the bigip_partition module is incorrect right now, so I'm adding code to make it correct. When it is done would you be content to have it accept a route_domain param (similar to what you do in the first step in your example there) and then follow that with the bigip_selfip module accepting a "partition" param (similar to the bigip_user module) so that it would pin that self-ip to the partition and then the partition would have the RD set?

Lemme know. Thanks!

**Comment by hemskgren** [comment]
Hi

That shuld work now when partition work.
I tried to add selfip to a vlan not in /common it passed but no IP was set.

If you add Rd/partition option I will verify.

Regards
Christer

**Comment by caphrim007** [comment]
OK, lemme address and test the vlan request. I'll update this issue when its ready to be tested by others. Thanks!

**Comment by manuadoor** [comment]
Are we talking about the issue of not having an option to create a self IP for a Vlan in a different route domain other than "0"?

**Comment by hemskgren** [comment]
@manuadoor correct

**Comment by caphrim007** [comment]
@hemskgren and @manuadoor this should now work. try with current module
