### ISSUE TITLE
LTM persistence profile 

### ISSUE THREAD

**Issue by vs926p** [F5Networks/f5-ansible#638]
##### ISSUE TYPE

 - Feature Idea

##### COMPONENT NAME
LTM persistence profile. 

##### ANSIBLE VERSION

```

```

##### PYTHON VERSION

```

```

##### BIGIP VERSION

```

```

##### LIBRARY VERSIONS

```

```

##### SUMMARY
Need a module to support persistence profile creation in an LTM. 
Tmsh command for the same:
create ltm persistence source-addr MSP-SOURCE-ADDRESS-TRANSPARENT hash-algorithm carp match-across-services enabled match-across-virtuals enabled

##### STEPS TO REPRODUCE

```

```

##### ACTUAL RESULTS

```

```

**Comment by Dan0maN** [comment]
It doesn't appear that I can +1 on the first post.  Adding this to be a +1.  We need to have the ability to configure every object type via an ansible module.  Without the individual modules, we are forced to run arbitrary non-idempotent commands on the device.  This defeats the purpose of using ansible as a whole (we could ssh to the device and run them ourselves).

**Comment by caphrim007** [comment]
@Dan0maN when you say every object type, can you be more specific?

**Comment by Dan0maN** [comment]
@caphrim007 Sure.  I mean that if we are completely automating our environments using a configuration management tool, then we need the ability to configure every item on the device that we would normally change using the WebUI or CLI.  We need to be able to configure every type of monitor, protocol profile and persistence profile.

**Comment by caphrim007** [comment]
@Dan0maN I don't have my PC in front of me, so excuse the next question, "type" in some cases (like monitors) requires that different modules be created for each (due to the wildly different config options for them)

In other cases, "type" is a field that we put in the module because there is little variety between them (tcp profile would be an example).

I assume you mean both.

For the first type, can you file issues for what you need? One issue per feature. For the second one, you can be more general in the issue (I need foo profile) and we can hash out the details in the comments.

Also, ping me offline at my email (in my GitHub profile) because I thought my PMs or AMs said they were arranging a phone con, but then didn't follow through. So I want to see how we can better serve your requirements (maybe with ihealth or other data)
