### ISSUE TITLE
support network ip's on a virtual server

### ISSUE THREAD

**Issue by caphrim007** [F5Networks/f5-ansible#650]
today, the virtuals only support a /32 ip. They can technically support "network" ips though, like /27. Or, "all addresses" like 0.0.0.0/0.

The module should support this.

**Comment by realged13** [comment]
This would be awesome.  Thanks!

**Comment by slavkv** [comment]
@caphrim007 any chance it will be supported soon?

Both for IPv4 and IPv6.

**Comment by mojr13** [comment]
Hello,
it looks like this fix broke the bigip_virtual_server functionality. Unless you specify 0.0.0.0 address it will not work. The error log is: 

An exception occurred during task execution. To see the full traceback, use -vvv. The error was: ansible.module_utils.compat.ipaddress.AddressValueError: '1.1.1.1' does not appear to be an IPv4 or IPv6 network. Did you pass in a bytes (str in Python 2) instead of a unicode object?

Traceback:
ansible-playbook 2.8.0.dev0
  config file = /root/.ansible.cfg
  configured module search path = [u'/root/f5-ansible/library/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible-playbook
  python version = 2.7.5 (default, May  3 2017, 07:55:04) [GCC 4.8.5 20150623 (Red Hat 4.8.5-14)]
Using /root/.ansible.cfg as config file
/root/playbooks/hosts did not meet host_list requirements, check plugin documentation if this is unexpected
/root/playbooks/hosts did not meet script requirements, check plugin documentation if this is unexpected
Parsed /root/playbooks/hosts inventory source with ini plugin

PLAYBOOK: test.yml **************************************************************************************************************************************************************************************************************************
1 plays in test.yml

PLAY [Set up a BIG-IP HA pair] **************************************************************************************************************************************************************************************************************
META: ran handlers

TASK [Add  Virtual Server SSL to HTTP] ******************************************************************************************************************************************************************************************************
task path: /root/playbooks/test.yml:14
<localhost> ESTABLISH LOCAL CONNECTION FOR USER: root
<localhost> EXEC /bin/sh -c 'echo ~root && sleep 0'
<localhost> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /root/.ansible/tmp/ansible-tmp-1541670614.69-63886159307770 `" && echo ansible-tmp-1541670614.69-63886159307770="` echo /root/.ansible/tmp/ansible-tmp-1541670614.69-63886159307770 `" ) && sleep 0'
Using module file /root/f5-ansible/library/modules/bigip_virtual_server.py
<localhost> PUT /root/.ansible/tmp/ansible-local-53099uEKYy9/tmpW3MyY5 TO /root/.ansible/tmp/ansible-tmp-1541670614.69-63886159307770/AnsiballZ_bigip_virtual_server.py
<localhost> EXEC /bin/sh -c 'chmod u+x /root/.ansible/tmp/ansible-tmp-1541670614.69-63886159307770/ /root/.ansible/tmp/ansible-tmp-1541670614.69-63886159307770/AnsiballZ_bigip_virtual_server.py && sleep 0'
<localhost> EXEC /bin/sh -c '/usr/bin/python /root/.ansible/tmp/ansible-tmp-1541670614.69-63886159307770/AnsiballZ_bigip_virtual_server.py && sleep 0'
<localhost> EXEC /bin/sh -c 'rm -f -r /root/.ansible/tmp/ansible-tmp-1541670614.69-63886159307770/ > /dev/null 2>&1 && sleep 0'
The full traceback is:
Traceback (most recent call last):
  File "/root/.ansible/tmp/ansible-tmp-1541670614.69-63886159307770/AnsiballZ_bigip_virtual_server.py", line 113, in <module>
    _ansiballz_main()
  File "/root/.ansible/tmp/ansible-tmp-1541670614.69-63886159307770/AnsiballZ_bigip_virtual_server.py", line 105, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/root/.ansible/tmp/ansible-tmp-1541670614.69-63886159307770/AnsiballZ_bigip_virtual_server.py", line 48, in invoke_module
    imp.load_module('__main__', mod, module, MOD_DESC)
  File "/tmp/ansible_bigip_virtual_server_payload_p44_aK/__main__.py", line 3181, in <module>
  File "/tmp/ansible_bigip_virtual_server_payload_p44_aK/__main__.py", line 3172, in main
  File "/tmp/ansible_bigip_virtual_server_payload_p44_aK/__main__.py", line 2882, in exec_module
  File "/tmp/ansible_bigip_virtual_server_payload_p44_aK/__main__.py", line 2894, in present
  File "/tmp/ansible_bigip_virtual_server_payload_p44_aK/__main__.py", line 2910, in update
  File "/tmp/ansible_bigip_virtual_server_payload_p44_aK/__main__.py", line 2918, in should_update
  File "/tmp/ansible_bigip_virtual_server_payload_p44_aK/__main__.py", line 2948, in _update_changed_options
  File "/tmp/ansible_bigip_virtual_server_payload_p44_aK/__main__.py", line 2549, in compare
  File "/tmp/ansible_bigip_virtual_server_payload_p44_aK/__main__.py", line 2613, in destination
  File "/tmp/ansible_bigip_virtual_server_payload_p44_aK/__main__.py", line 1466, in destination_tuple
  File "/tmp/ansible_bigip_virtual_server_payload_p44_aK/ansible_bigip_virtual_server_payload.zip/ansible/module_utils/network/f5/ipaddress.py", line 103, in compress_address
    return less
  File "/tmp/ansible_bigip_virtual_server_payload_p44_aK/ansible_bigip_virtual_server_payload.zip/ansible/module_utils/compat/ipaddress.py", line 253, in ip_network
    """
ansible.module_utils.compat.ipaddress.AddressValueError: '1.1.1.1' does not appear to be an IPv4 or IPv6 network. Did you pass in a bytes (str in Python 2) instead of a unicode object?

fatal: [10.212.152.4 -> localhost]: FAILED! => {
    "changed": false,
    "module_stderr": "Traceback (most recent call last):\n  File \"/root/.ansible/tmp/ansible-tmp-1541670614.69-63886159307770/AnsiballZ_bigip_virtual_server.py\", line 113, in <module>\n    _ansiballz_main()\n  File \"/root/.ansible/tmp/ansible-tmp-1541670614.69-63886159307770/AnsiballZ_bigip_virtual_server.py\", line 105, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/root/.ansible/tmp/ansible-tmp-1541670614.69-63886159307770/AnsiballZ_bigip_virtual_server.py\", line 48, in invoke_module\n    imp.load_module('__main__', mod, module, MOD_DESC)\n  File \"/tmp/ansible_bigip_virtual_server_payload_p44_aK/__main__.py\", line 3181, in <module>\n  File \"/tmp/ansible_bigip_virtual_server_payload_p44_aK/__main__.py\", line 3172, in main\n  File \"/tmp/ansible_bigip_virtual_server_payload_p44_aK/__main__.py\", line 2882, in exec_module\n  File \"/tmp/ansible_bigip_virtual_server_payload_p44_aK/__main__.py\", line 2894, in present\n  File \"/tmp/ansible_bigip_virtual_server_payload_p44_aK/__main__.py\", line 2910, in update\n  File \"/tmp/ansible_bigip_virtual_server_payload_p44_aK/__main__.py\", line 2918, in should_update\n  File \"/tmp/ansible_bigip_virtual_server_payload_p44_aK/__main__.py\", line 2948, in _update_changed_options\n  File \"/tmp/ansible_bigip_virtual_server_payload_p44_aK/__main__.py\", line 2549, in compare\n  File \"/tmp/ansible_bigip_virtual_server_payload_p44_aK/__main__.py\", line 2613, in destination\n  File \"/tmp/ansible_bigip_virtual_server_payload_p44_aK/__main__.py\", line 1466, in destination_tuple\n  File \"/tmp/ansible_bigip_virtual_server_payload_p44_aK/ansible_bigip_virtual_server_payload.zip/ansible/module_utils/network/f5/ipaddress.py\", line 103, in compress_address\n    return less\n  File \"/tmp/ansible_bigip_virtual_server_payload_p44_aK/ansible_bigip_virtual_server_payload.zip/ansible/module_utils/compat/ipaddress.py\", line 253, in ip_network\n    \"\"\"\nansible.module_utils.compat.ipaddress.AddressValueError: '1.1.1.1' does not appear to be an IPv4 or IPv6 network. Did you pass in a bytes (str in Python 2) instead of a unicode object?\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
    "rc": 1
}
        to retry, use: --limit @/root/playbooks/test.retry

PLAY RECAP **********************************************************************************************************************************************************************************************************************************
10.212.152.4               : ok=0    changed=0    unreachable=0    failed=1    skipped=0

**Comment by wojtek0806** [comment]
This looks like an issue with py 2.x string representation. i will amend this so that we pass unicode, to facilitate py 2.x situations
