### ISSUE TITLE
add support for renewing self-signed device certificates

### ISSUE THREAD

**Issue by caphrim007** [F5Networks/f5-ansible#711]
relevant KB is here https://support.f5.com/csp/article/K6353

customer has a need to do this across a fleet of viprs and guests. Doesn't want to do it manually. I don't blame them.

**Comment by caphrim007** [comment]
See FMFA-150

**Comment by vmpr** [comment]
+1 would be nice to have a way to deploy the device certificate with ansible, cheers!

**Comment by cjohnweb** [comment]
I would also like this. A module to upload SSL Certificate for device interface should have been done first before Client SSL Profile, because if your Device Certificates expire then you can't use Ansible over the RESTful API to update the Client SSL Profile. Client SSL Profile now has become next to completely useless in light of this.

Is there an ETA on completion of Ansible module for System Device Certificate?
Is there a route on the API that will allow upload of System Device Certificate?
Is there a CLI command that will set the System Device Certificate?

In light of the lack of an Ansible plugin is there any other "automatable" way to accomplish this?

**Comment by wojtek0806** [comment]
related most likely #1275

**Comment by wojtek0806** [comment]
@cjohnweb 
For renewing expired CA-signed SSL certificates not the self-signed ones generated on the BIGIP you need to use traditional methods of file transfer over SSH to transfer the relevant files, for this ansible copy module would suffice:

https://docs.ansible.com/ansible/latest/modules/copy_module.html

We will not implement file copy over SSH as these functions already exists in core ansible modules and they should work with the F5 unit, provided you have user with full bash access. Furthermore if you are using CA-signed SSL certificates, effectively you need to copy the new certificate files over to BIG-IP with ansible copy module, and run TMSH commands with bigip_command module as per the KB article:

https://support.f5.com/csp/article/K42531434

While we have bigip_device_httpd module albeit we need to add some of the options to do what the commands do. The module would only work on REST, so you must revert to bigip_command module as it supports SSH transport type.

If you would need such functionality i.e to renew CA signed device certs, then we would need to use a role rather than a module, please open a separate issue referencing this one if this is needed.

**Comment by wojtek0806** [comment]
The plan for this module would be to have both SSH and REST support for generating CSR and renewal for self-signed device certificates as per the linked KB article. The reason for adding SSH transport is so that should the self-signed cert expire we would not be able to use REST so user would have a way getting out of the situation.

**Comment by wojtek0806** [comment]
In addition we will add the option to create a new self-signed device/key as per this KB:

https://support.f5.com/csp/article/K9114
