### ISSUE TITLE
BigIP Node New IP Address same Name

### ISSUE THREAD

**Issue by mitchellmaler** [F5Networks/f5-ansible#811]
Is it possible to update an existing node with a new IP address? 
Right now I rebuild servers once in a while and the ip will change but the name will not. 

Do I have to remove the node from pools and then remove the node completely then add it back or can I just update the existing node to point to the new IP address?

**Comment by caphrim007** [comment]
@mitchellmaler no I think not. This is a limitation of the BIG-IP system. If you're doing this, you might try creating nodes using FQDNs and then updating DNS. Otherwise, deleting and re-creating is the only way as there are no tmsh commands, web ui, or REST API calls that can be made to change a node's IP address.

**Comment by mitchellmaler** [comment]
Okay sounds good. Currently, I am doing the delete and recreate. I was just hoping there was an easier way.

**Comment by caphrim007** [comment]
alternatively, you can add the new machines to your pools and then walk through and delete any old pool members with the `preserve_node: no` to delete both the member and its node
